{{- if eq .Values.backup.method "plugin" }}
{{- if not .Values.backup.objectStore.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpg.secrets.objectStoreName" . }}
  labels:
    {{- include "cnpg.labels" . | trim | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  access-key-id: {{ required "Access Key ID for backup is required without existing secret" .Values.backup.objectStore.accessKeyId }}
  secret-access-key: {{ required "Secret Access Key for backup is required without existing secret" .Values.backup.objectStore.secretAccessKey }}
  {{- with .Values.backup.objectStore.accessSessionToken }}
  access-session-token: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
