{{- if not .Values.cluster.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpg.secrets.userName" . }}
  labels:
    {{- include "cnpg.labels" . | trim | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/basic-auth
data:
  username: {{ required "username is required with no existing secret" .Values.cluster.username | b64enc }}
  password: {{ required "password is required with no existing secret" .Values.cluster.password | b64enc }}
{{- end }}
