#!/bin/bash


helm repo add dandydev https://dandydeveloper.github.io/charts
helm repo add cnpg https://cloudnative-pg.github.io/charts
helm install redis dandydev/redis-ha \
    --set "replicas=1,auth=true,redisPassword=password
helm install postgresql cnpg cnpg/cloudnative-pg

kubectl apply -f charts/mastodon/ci/test-postgres-cluster.yaml
