#!/bin/bash
set -e

echo "##### Adding Helm Repositories #####"
echo
helm repo add dandydev https://dandydeveloper.github.io/charts
helm repo add cnpg https://cloudnative-pg.github.io/charts

echo "##### Installing databases #####"
echo
helm install redis dandydev/redis-ha \
    --set "replicas=2,auth=true,redisPassword=password" \
    --namespace default
helm install cnpg cnpg/cloudnative-pg \
    --namespace default
kubectl -n cnpg-system rollout status deployment/cnpg-cloudnative-pg
kubectl apply -n mastodon -f charts/mastodon/ci/test-postgres-cluster.yaml

echo
echo "Waiting for pods to become ready..."
kubectl -n default rollout status --timeout=600s sts/redis-redis-ha-server
kubectl wait -n default --for=condition=Ready --timeout=300s cluster/postgres
