apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fediscoverer.fullname" . }}-jobs
  labels:
    {{- include "fediscoverer.labels" . | nindent 4 }}
    joinmastodon.org/component: fediscoverer-jobs
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fediscoverer.selectorLabels" . | nindent 6 }}
      joinmastodon.org/component: fediscoverer-jobs
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fediscoverer.selectorLabels" . | nindent 8 }}
        joinmastodon.org/component: fediscoverer-jobs
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-jobs
          command: ["bin/jobs"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.secretKeyBase.secretKeyRef.name }}
                  key: {{ .Values.config.secretKeyBase.secretKeyRef.key }}
            - name: DATABASE_URL
              value: {{ include "fediscoverer.database.uri" . }}
            - name: FEDISCOVERER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.database.password.secretKeyRef.name }}
                  key: {{ .Values.config.database.password.secretKeyRef.key }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
