{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fediscoverer.secrets.secretKeyBase" . }}
  labels:
    {{- include "fediscoverer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  secret-key-base: {{ required "secretKeyBase is required with no existing secret" .Values.config.secretKeyBase | b64enc }}
{{- end }}
