apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: {{ include "dragonfly.fullname" . }}-sidekiq
  labels:
    {{- include "dragonfly.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  {{- if .Values.nodeSelector }}
  nodeSelector:
    {{- with .Values.nodeSelector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  replicas: 1
  args:
    - "--dbfilename=dragonflydbSnapshot"
  snapshot:
    cron: "{{ .Values.snapshot.cron }}"
    persistentVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.snapshot.storage }}
  {{- if .Values.resources }}
  resources:
    {{- with .Values.resources }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
