apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "cnpg.fullname" . }}
  labels:
    {{- include "cnpg.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  instances: {{ .Values.instances }}
  imageName: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  {{- if eq .Values.backup.method "plugin" }}
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: {{ include "cnpg.store.name" . }}
  {{- end }}
  bootstrap:
    initdb:
      database: {{ .Values.cluster.dbname }}
      owner: {{ .Values.cluster.owner }}
      secret:
        name: {{ .Values.cluster.secret }}
      postInitSQL:
        - CREATE DATABASE {{ .Values.cluster.dbname }} OWNER {{ .Values.cluster.owner }}
  storage:
    size: {{ .Values.cluster.storage }}
  monitoring:
    enablePodMonitor: true
  affinity:
    {{- with .Values.affinity }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
