{{- $context := . }}
{{- range .Values.mastodon.sidekiq.workers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mastodon.fullname" $context }}-sidekiq-{{ .name }}
  labels:
    {{- include "mastodon.labels" $context | trim | nindent 4 }}
    {{- include "mastodon.userLabels" $context | trim | nindent 4 }}
    {{- with $context.Values.mastodon.sidekiq.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: sidekiq-{{ .name }}
    app.kubernetes.io/part-of: rails
  annotations:
    {{- include "mastodon.userDeployAnnotations" $context | trim | nindent 4 }}
    {{- with $context.Values.mastodon.sidekiq.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if (has "scheduler" .queues) }}
    {{- if (gt (int .replicas) 1) }}
      {{ fail "The scheduler queue should never have more than 1 replicas" }}
    {{- end }}
  {{- end }}
  {{- if $context.Values.mastodon.sidekiq.updateStrategy }}
  strategy: {{- toYaml $context.Values.mastodon.sidekiq.updateStrategy | nindent 4 }}
  {{- end }}
  replicas: {{ .replicas }}
  {{- if (ne (toString $context.Values.mastodon.revisionHistoryLimit) "<nil>") }}
  revisionHistoryLimit: {{ $context.Values.mastodon.revisionHistoryLimit }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mastodon.selectorLabels" $context | nindent 6 }}
      app.kubernetes.io/component: sidekiq-{{ .name }}
      app.kubernetes.io/part-of: rails
  template:
    metadata:
      labels:
        {{- include "mastodon.selectorLabels" $context | trim | nindent 8 }}
        {{- include "mastodon.podUserLabels" $context | trim | nindent 8 }}
        {{- with $context.Values.mastodon.sidekiq.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: sidekiq-{{ .name }}
        app.kubernetes.io/part-of: rails
      annotations:
        {{- include "mastodon.userPodAnnotations" $context | trim | nindent 8 }}
        {{- include "mastodon.rollingPodAnnotations" $context | trim | nindent 8 }}
        {{- with $context.Values.mastodon.sidekiq.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        # roll the pods to pick up any db migrations or other changes
        {{- include "mastodon.rollingPodAnnotations" $context | nindent 8 }}
    spec:
      {{- include "mastodon.deployment.specWithVolumes" $context | nindent 6 }}
      {{- with coalesce $context.Values.mastodon.sidekiq.podSecurityContext $context.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $context.Chart.Name }}
          {{- include "mastodon.container.specWithVolumes" $context | nindent 10 }}
          {{- with $context.Values.mastodon.sidekiq.securityContext | default $context.Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ coalesce (dig "image" "repository" false .) $context.Values.image.repository }}:{{ coalesce (dig "image" "tag" false .) $context.Values.image.tag $context.Chart.AppVersion }}"
          imagePullPolicy: {{ $context.Values.image.pullPolicy }}
          command:
            - bundle
            - exec
            - sidekiq
            - -c
            - {{ .concurrency | quote }}
            {{- range .queues }}
            - -q
            - {{ . | quote }}
            {{- end }}
          env:
            {{- include "mastodon.secrets.s3" $context | nindent 12 }}
            {{- include "mastodon.secrets.database" $context | nindent 12 }}
            {{- include "mastodon.secrets.redis" $context | nindent 12 }}
            {{- include "mastodon.secrets.smtp" $context | nindent 12 }}
            {{- if $context.Values.elasticsearch.enabeld }}
            {{- include "mastodon.secrets.elasticsearch" $context | nindent 12 }}\
            {{- end }}
            {{- if $context.Values.mastodon.deepl.enabled }}
            {{- include "mastodon.secrets.deepl" $context | nindent 12 }}
            {{- end }}
            {{- if $context.Values.mastodon.cacheBuster.enabled }}
            {{- include "mastodon.secrets.cacheBuster" $context | nindent 12 }}
            {{- end }}
            {{- if or $context.Values.mastodon.sidekiq.otel.enabled (and $context.Values.mastodon.otel.enabled (ne $context.Values.mastodon.sidekiq.otel.enabled false)) }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ coalesce $context.Values.mastodon.sidekiq.otel.endpointUri $context.Values.mastodon.otel.endpointUri }}
            - name: OTEL_SERVICE_NAME_PREFIX
              value: {{ coalesce $context.Values.mastodon.sidekiq.otel.namePrefix $context.Values.mastodon.otel.namePrefix }}
            - name: OTEL_SERVICE_NAME_SEPARATOR
              value: "{{ coalesce $context.Values.mastodon.sidekiq.otel.nameSeparator $context.Values.mastodon.otel.nameSeparator }}"
            {{- end }}
            {{- if $context.Values.mastodon.metrics.prometheus.enabled }}
            - name: MASTODON_PROMETHEUS_EXPORTER_ENABLED
              value: "true"
            - name: MASTODON_PROMETHEUS_EXPORTER_LOCAL
              value: "true"
            - name: MASTODON_PROMETHEUS_EXPORTER_HOST
              value: "0.0.0.0"
            - name: MASTODON_PROMETHEUS_EXPORTER_PORT
              value: "{{ $context.Values.mastodon.metrics.prometheus.port }}"
            {{- if $context.Values.mastodon.metrics.prometheus.sidekiq.detailed }}
            - name: MASTODON_PROMETHEUS_EXPORTER_SIDEKIQ_DETAILED_METRICS
              value: "true"
            {{- end }}
            {{- end }}
            {{- range $k, $v := $context.Values.mastodon.sidekiq.extraEnvVars }}
            - name: {{ $k }}
              value: {{ quote $v }}
            {{- end }}
          {{- if $context.Values.mastodon.metrics.prometheus.enabled }}
          ports:
            - name: prometheus
              containerPort: {{ $context.Values.mastodon.metrics.prometheus.port }}
          {{- end }}
          {{- if $context.Values.mastodon.sidekiq.readinessProbe.enabled }}
          readinessProbe:
            failureThreshold: {{ default 10 $context.Values.mastodon.sidekiq.readinessProbe.failureThreshold }}
            exec:
              command:
              - cat
              - {{ required "A valid sidekiq readiness path is required." $context.Values.mastodon.sidekiq.readinessProbe.path }}
            initialDelaySeconds: {{ default 10 $context.Values.mastodon.sidekiq.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 2 $context.Values.mastodon.sidekiq.readinessProbe.periodSeconds }}
            successThreshold: {{ default 1 $context.Values.mastodon.sidekiq.readinessProbe.successThreshold }}
            timeoutSeconds: {{ default 1 $context.Values.mastodon.sidekiq.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- with coalesce $context.Values.mastodon.sidekiq.resources $context.Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with coalesce .nodeSelector $context.Values.mastodon.sidekiq.nodeSelector $context.Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with coalesce .affinity $context.Values.mastodon.sidekiq.affinity $context.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .topologySpreadConstraints $context.Values.mastodon.sidekiq.topologySpreadConstraints $context.Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .tolerations $context.Values.mastodon.sidekiq.tolerations $context.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
