apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mastodon.fullname" . }}-streaming
  labels:
    {{- include "mastodon.labels" . | trim | nindent 4 }}
    {{- include "mastodon.userLabels" . | trim | nindent 4 }}
    {{- with .Values.mastodon.streaming.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "mastodon.userDeployAnnotations" . | trim | nindent 4 }}
    {{- with .Values.mastodon.streaming.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.mastodon.streaming.replicas }}
  {{- if (ne (toString .Values.mastodon.revisionHistoryLimit) "<nil>") }}
  revisionHistoryLimit: {{ .Values.mastodon.revisionHistoryLimit }}
  {{- end }}
  {{- if .Values.mastodon.streaming.updateStrategy }}
  strategy: {{- toYaml .Values.mastodon.streaming.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mastodon.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: streaming
  template:
    metadata:
      labels:
        {{- include "mastodon.selectorLabels" . | trim | nindent 8 }}
        {{- include "mastodon.podUserLabels" . | trim | nindent 8 }}
        {{- with .Values.mastodon.streaming.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: streaming
      annotations:
        {{- include "mastodon.userPodAnnotations" . | trim | nindent 8 }}
        {{- include "mastodon.rollingPodAnnotations" . | trim | nindent 8 }}
        {{- with .Values.mastodon.streaming.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "mastodon.deployment.spec" . | trim | nindent 6 }}
      {{- with coalesce .Values.mastodon.streaming.podSecurityContext .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mastodon.streaming.extraCerts }}
      volumes:
        {{- $name := .name | default "extra-certs" }}
          - name: {{ $name }}
            secret:
              secretName: {{ .existingSecret }}
              items:
              - key: ca.crt
                path: trusted-ca.crt
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}-streaming
          {{- include "mastodon.container.spec" . | trim | nindent 10 }}
          {{- with coalesce .Values.mastodon.streaming.securityContext .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.mastodon.streaming.image.repository }}:{{ coalesce .Values.mastodon.streaming.image.tag .Values.image.tag .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - node
            - ./streaming
          {{- with .Values.mastodon.streaming.extraCerts }}
          volumeMounts:
            {{- $name := .name | default "extra-certs" }}
            - name: {{ $name }}
              mountPath: "/usr/local/share/ca-certificates"
            {{- end }}
            {{- with .Values.volumeMounts }}
            volumeMounts:
              {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: "PORT"
              value: {{ .Values.mastodon.streaming.port | quote }}
            {{- with .Values.mastodon.streaming.extraCerts }}
            - name: "NODE_EXTRA_CA_CERTS"
              value: "/usr/local/share/ca-certificates/trusted-ca.crt"
            {{- with .sslMode }}
            - name: "DB_SSLMODE"
              value: {{ . }}
            {{- end }}
            {{- end }}
            {{- with .Values.postgresql.readReplica.hostname }}
            - name: "DB_HOST"
              value: {{ . }}
            {{- end }}
            {{- include "mastodon.secrets.database" . | nindent 12 }}
            {{- include "mastodon.secrets.redis" . | nindent 12 }}
            {{- range $k, $v := .Values.mastodon.streaming.extraEnvVars }}
            - name: {{ $k }}
              value: {{ quote $v }}
            {{- end }}
          ports:
            - name: streaming
              containerPort: {{ .Values.mastodon.streaming.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/streaming/health
              port: streaming
          readinessProbe:
            httpGet:
              path: /api/v1/streaming/health
              port: streaming
          startupProbe:
            httpGet:
              path: /api/v1/streaming/health
              port: streaming
            initialDelaySeconds: 5
            failureThreshold: 15
            periodSeconds: 5
          {{- with coalesce .Values.mastodon.streaming.resources .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with coalesce .Values.mastodon.streaming.nodeSelector .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.mastodon.streaming.affinity .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.mastodon.streaming.topologySpreadConstraints .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.mastodon.streaming.tolerations .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
