apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mastodon.fullname" . }}-web
  labels:
    {{- include "mastodon.labels" . | trim | nindent 4 }}
    {{- include "mastodon.userLabels" . | trim | nindent 4 }}
    {{- with .Values.mastodon.web.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "mastodon.userDeployAnnotations" . | trim | nindent 4 }}
    {{- with .Values.mastodon.web.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.mastodon.web.replicas }}
  {{- if (ne (toString .Values.mastodon.revisionHistoryLimit) "<nil>") }}
  revisionHistoryLimit: {{ .Values.mastodon.revisionHistoryLimit }}
  {{- end }}
  {{- if .Values.mastodon.web.updateStrategy }}
  strategy: {{- toYaml .Values.mastodon.web.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mastodon.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
      app.kubernetes.io/part-of: rails
  template:
    metadata:
      labels:
        {{- include "mastodon.selectorLabels" . | trim | nindent 8 }}
        {{- include "mastodon.podUserLabels" . | trim | nindent 8 }}
        {{- with .Values.mastodon.web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: rails
      annotations:
        {{- include "mastodon.userPodAnnotations" . | trim | nindent 8 }}
        {{- include "mastodon.rollingPodAnnotations" . | trim | nindent 8 }}
        {{- with .Values.mastodon.web.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "mastodon.deployment.specWithVolumes" . | trim | nindent 6 }}
      {{- with coalesce .Values.mastodon.web.podSecurityContext .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-web
          {{- include "mastodon.container.specWithVolumes" . | trim | nindent 10 }}
          {{- with coalesce .Values.mastodon.web.securityContext .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ coalesce .Values.mastodon.web.image.repository .Values.image.repository }}:{{ coalesce .Values.mastodon.web.image.tag .Values.image.tag .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bundle
            - exec
            - puma
            - -C
            - config/puma.rb
          env:
            - name: "PORT"
              value: {{ .Values.mastodon.web.port | quote }}
            {{- if .Values.mastodon.web.minThreads }}
            - name: "MIN_THREADS"
              value: {{ .Values.mastodon.web.minThreads | quote }}
            {{- end }}
            {{- if .Values.mastodon.web.maxThreads }}
            - name: "MAX_THREADS"
              value: {{ .Values.mastodon.web.maxThreads | quote }}
            {{- end }}
            {{- if .Values.mastodon.web.workers }}
            - name: "WEB_CONCURRENCY"
              value: {{ .Values.mastodon.web.workers | quote }}
            {{- end }}
            {{- if .Values.mastodon.web.persistentTimeout }}
            - name: "PERSISTENT_TIMEOUT"
              value: {{ .Values.mastodon.web.persistentTimeout | quote }}
            {{- end }}
            {{- include "mastodon.secrets.s3" . | nindent 12 }}
            {{- include "mastodon.secrets.database" . | nindent 12 }}
            {{- include "mastodon.secrets.redis" . | nindent 12 }}
            {{- if .Values.elasticsearch.enabled }}
            {{- include "mastodon.secrets.elasticsearch" . | nindent 12 }}
            {{- end }}
            {{- if .Values.mastodon.deepl.enabled }}
            {{- include "mastodon.secrets.deepl" . | nindent 12 }}
            {{- end }}
            {{- if .Values.mastodon.hcaptcha.enabled }}
            {{- include "mastodon.secrets.hcaptcha" . | nindent 12 }}
            {{- end }}
            {{- if .Values.mastodon.cacheBuster.enabled }}
            {{- include "mastodon.secrets.cacheBuster" . | nindent 12 }}
            {{- end }}
            {{- if or .Values.mastodon.web.otel.enabled (and .Values.mastodon.otel.enabled (ne .Values.mastodon.web.otel.enabled false)) }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ coalesce .Values.mastodon.web.otel.endpointUri .Values.mastodon.otel.endpointUri }}
            - name: OTEL_SERVICE_NAME_PREFIX
              value: {{ coalesce .Values.mastodon.web.otel.namePrefix .Values.mastodon.otel.namePrefix }}
            - name: OTEL_SERVICE_NAME_SEPARATOR
              value: "{{ coalesce .Values.mastodon.web.otel.nameSeparator .Values.mastodon.otel.nameSeparator }}"
            {{- end }}
            {{- if .Values.mastodon.metrics.prometheus.enabled }}
            - name: MASTODON_PROMETHEUS_EXPORTER_ENABLED
              value: "true"
            - name: PROMETHEUS_EXPORTER_HOST
              value: "127.0.0.1"
            - name: PROMETHEUS_EXPORTER_PORT
              value: "{{ .Values.mastodon.metrics.prometheus.port }}"
            {{- if .Values.mastodon.metrics.prometheus.web.detailed }}
            - name: MASTODON_PROMETHEUS_EXPORTER_WEB_DETAILED_METRICS
              value: "true"
            {{- end }}
            {{- end }}
            {{- range $k, $v := .Values.mastodon.web.extraEnvVars }}
            - name: {{ $k }}
              value: {{ quote $v }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.mastodon.web.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            failureThreshold: 30
            periodSeconds: 5
          {{- with coalesce .Values.mastodon.web.resources .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.mastodon.metrics.prometheus.enabled }}
        - name: prometheus-exporter
          image: "{{ coalesce .Values.mastodon.web.image.repository .Values.image.repository }}:{{ coalesce .Values.mastodon.web.image.tag .Values.image.tag .Chart.AppVersion }}"
          command:
            - ./bin/prometheus_exporter
          args:
            - "--bind"
            - "0.0.0.0"
            - "--port"
            - "{{ .Values.mastodon.metrics.prometheus.port }}"
          resources:
            requests:
              cpu: "0.1"
              memory: "180M"
            limits:
              cpu: "0.5"
              memory: "250M"
          ports:
            - name: prometheus
              containerPort: {{ .Values.mastodon.metrics.prometheus.port }}
        {{- end }}
      {{- with coalesce .Values.mastodon.web.nodeSelector .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.mastodon.web.affinity .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.mastodon.web.topologySpreadConstraints .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.mastodon.web.tolerations .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
