{{- if not .Values.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.secrets.redisName" . }}
  labels:
    {{- include "mastodon.labels" . | trim | nindent 4 }}
    {{- include "mastodon.userLabels" . | trim | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  password: {{ required "Redis password is required with no existing secret" .Values.redis.password | b64enc }}
{{- end }}
