{{- if not .Values.mastodon.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.secrets.secretName" . }}
  labels:
    {{- include "mastodon.labels" . | trim | nindent 4 }}
    {{- include "mastodon.userLabels" . | trim | nindent 4 }}
type: Opaque
data:
  SECRET_KEY_BASE: {{ required "secretKeyBase is required" (.Values.mastodon.secrets.secretKeyBase | b64enc | quote) }}
  VAPID_PRIVATE_KEY: {{ required "vapidPrivateKey is required" (.Values.mastodon.secrets.vapidPrivateKey | b64enc | quote) }}
  VAPID_PUBLIC_KEY: {{ required "vapidPublicKey is required" (.Values.mastodon.secrets.vapidPublicKey | b64enc | quote) }}
  ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: {{ required "arPrimaryKey is required" (.Values.mastodon.secrets.arPrimaryKey | b64enc | quote) }}
  ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: {{ required "arDeterministicKey is required" (.Values.mastodon.secrets.arDeterministicKey | b64enc | quote) }}
  ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: {{ required "arKeyDerivationSalt is required" (.Values.mastodon.secrets.arKeyDerivationSalt | b64enc | quote) }}
{{- end }}
