{{- if not .Values.mastodon.cacheBuster.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.secrets.cacheBusterName" . }}
  labels:
    {{- include "mastodon.labels" . | trim | nindent 4 }}
    {{- include "mastodon.userLabels" . | trim | nindent 4 }}
type: Opaque
data:
  auth-token: {{ required "Cache Buster auth token is required with no existing secret" .Values.mastodon.cacheBuster.authToken | b64enc }}
{{- end }}
