{{- if not .Values.mastodon.smtp.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.secrets.smtpName" . }}
  labels:
    {{- include "mastodon.labels" . | trim | nindent 4 }}
    {{- include "mastodon.userLabels" . | trim | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ required "SMTP username is required with no existing secret" .Values.mastodon.smtp.username | b64enc }}
  password: {{ required "SMTP password is required with no existing secret" .Values.mastodon.smtp.password | b64enc }}
{{- end }}
