{{- if not .Values.mastodon.hooks.s3Upload.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.secrets.s3UploadName" . }}
  labels:
    {{- include "mastodon.labels" . | trim | nindent 4 }}
    {{- include "mastodon.userLabels" . | trim | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"
type: kubernetes.io/basic-auth
data:
  AWS_SECRET_ACCESS_KEY: {{ required "Asset upload S3 access key ID is required with no existing secret" .Values.mastodon.hooks.s3Upload.accessKeyId | b64enc }}
  AWS_ACCESS_KEY_ID: {{ required "Asset upload S3  secret access key is required with no existing secret" .Values.mastodon.hooks.s3Upload.secretAccessKey | b64enc }}
{{- end }}
