apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    app: {{ template "pgbouncer.name" . }}
    chart: {{ template "pgbouncer.chart" . }}
    release: {{ .Release.Name }}
    {{- include "pgbouncer.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
    - port: 9127
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "pgbouncer.selectorLabels" . | nindent 4 }}
