apiVersion: v2
name: pgbouncer
description: |
  Creates a pgbouncer deployment.
home: https://joinmastodon.org
maintainers:
  - name: Mastodon
    url: https://joinmastodon.org
type: application
version: 1.4.0
appVersion: "1.24.0"
