# Default values for pgbouncer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

# Restarts the pods each time the chart is updated
# Otherwise you need to restart the pods manually if the settings
# or referenced secrets are updated
rollMe: true

image:
  repository: edoburu/pgbouncer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.21.0-p0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

# The secret containing the userlist.txt to deploy
usersSecretRef:
  name: pgbouncer-conf-users
  key: userlist.txt

databases:
  # name:
  #   host:
  #   port:
  #   user:
  #   dbname:

settings:
  adminUsers: []
  statsUsers: [pgbouncer_exporter]

  poolMode: transaction
  serverResetQuery: DISCARD ALL
  maxPreparedStatements: 0 # use 0 to disable the feature

  connectionLimits:
    maxClientConn: 2000
    defaultPoolSize: 200
    minPoolSize: 15
    reservePoolSize: 5
    reservePoolTimeout: 5

  logConnections: 0
  logDisconnections: 0
  logStats: 0
  logPoolerErrors: 1
  verbose: 0
  statsPeriod: 60
  serverLifetime: 3600
  serverIdleTimeout: 600
  serverConnectTimeout: 15
  serverLoginRetry: 15
  queryTimeout: 0
  queryWaitTimeout: 120
  clientIdleTimeout: 0
  clientLoginTimeout: 60

# pgbouncer will stop accepting queries immediatly when the pod needs to be stopped
# but will wait until all transactions end, or this amount of time
terminationGracePeriodSeconds: 120

prometheusExporter:
  enabled: true
  statsPgUser: pgbouncer_exporter
  statsPgPasswordSecretRef:
    name: pgbouncer-exporter-password
    key: password
  installServiceMonitor: false

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["all"]
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 6432

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
