apiVersion: v1
data:
  secret-key-base: ZjJmNGYwY2RiMDE3MjEyOTcxNDk3NjljZDkyMTM2OTk2YWZkZmNiN2Y0MjBlODhjMGQ4MzBkOTQzYWJkNDhkYzE5MGI2ZjA0ZGI3NWI2MzkzMDVhYWExODYxZGJkODg3NGFmZGE2MzJkZjRkMzQ3NzU2ZWY4ZWI3YzY4OWRmNGQ=
kind: Secret
metadata:
  name: mastodon-secrets
type: Opaque

