# Default values for fediscoverer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# General replica count for all pods
replicaCount: 1

image:
  repository: ghcr.io/mastodon/fediscoverer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# App-wide configuration
config:

  # URL that the service is accessible from
  domain: localhost

  # Fediverse secret key base.
  secretKeyBase:
    secretKeyRef:
      name: fediscoverer-secrets
      key: secret-key-base

  # PostgreSQL database connection information.
  # Some values for the database are hard-coded into the app, and must be:
  #   - Username: fediscoverer
  #   - Databases (all owned by fediscoverer):
  #     - fediscoverer_production
  #     - fediscoverer_production_cache
  #     - fediscoverer_production_queue
  database:
    host: localhost
    port: 5432
    password:
      secretKeyRef:
        name: postgresql-auth
        key: password

  # Whether to enable JSON logging
  jsonLogging: true

# Configuration for web pods
web:

  # Number of web pods
  # Will override the global replicaCount value
  replicaCount:

  # Tags for the deployment object
  tags:

  # Additional annotations for web pods
  # These will be added in addition to global podAnnotations
  podAnnotations:

  # Additional labels for web pods
  # These will be added in addition to other labels
  podlabels:

# Configuration for job pods
jobs:

  # Number of job pods
  # Will override the global replicaCount value
  replicaCount:

  # Tags for the deployment object
  tags:

  # Additional annotations for web pods
  # These will be added in addition to global podAnnotations
  podAnnotations:

  # Additional labels for jobs pods
  # These will be added in addition to other labels
  podlabels:

# Additional environment variables to set for all pods.
env:

# Whether to enable the prometheus exporter for monitoring
metrics:
  prometheus:
    enabled: false
    port: 9394

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: staging.fediscoverer.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
